### ISSUE TITLE
Easier of use

### ISSUE THREAD

**Issue by xx1182** [gochan-org/gochan#90] opened 2023-12-05 19:11 UTC
ESL:
Why no sqlite? It would be easier rather than having docker, just a simple .sh to "run".

Anyways when using ./build.py docker

```
# github.com/gochan-org/gochan/cmd/gochan
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
collect2: fatal error: cannot find 'ld'
compilation terminated.

Failed building gochan, see command output for details
Service 'gochan' failed to build: The command './build.py' returned a non-zero code: 1
Failed starting a docker container, exited with status code 1
```

**Comment by Eggbertx** [comment] 2023-12-05 20:01
Gochan does have SQLite support, set `DBtype` in gochan.json to sqlite3. Though I just checked the example JSON configuration file, and it looks like I neglected to make that clear when I readded support for it. If you set `DBtype` in your configuration file to sqlite3, `DBhost` should be path to the database, which will be created if it doesn't already exist.

As for the Docker issue, I wasn't able to reproduce it, what is your host OS?

**Comment by Eggbertx** [comment] 2023-12-05 23:28
Just in case, can you confirm that you have ld installed on the host? I don't think it needs it, but I figure it might be worth confirming that you have the gcc toolchain installed

**Comment by xx1182** [comment] 2023-12-06 09:12
> Just in case, can you confirm that you have ld installed on the host? I don't think it needs it, but I figure it might be worth confirming that you have the gcc toolchain installed
Ok, it's a Chromebook with the Linux Dev Enviroment.
As you can see from here, ld is installed:
![Firsto Remote Desktop](https://github.com/gochan-org/gochan/assets/6748908/3fb25ec9-6186-43d6-823b-cb5de0b9d713)

Secondly, since the docker didn't work, I tried building it(./build.py I guess?) there are multiple problems:
First, you have to create a log dir, it doesn't create it automatically where you set to.
Second, I've tried running as current user and it says gochan is not owner, do I have to make a gochan user? Group? Tried a second time with Sudo and there is another error.
Regards.
![Uploading Second Remote Desktop.jpg…]()

**Comment by xx1182** [comment] 2023-12-06 18:57
Yes ok I didn't have sqlite installed, sorry I didn't check.
But gcc is installed.

**Comment by xx1182** [comment] 2023-12-06 19:52
Ok, got it working, set webroot to /img/ and set my reverse proxy to /img/
The home button gets built to /img rather than /img/(ending slash).

The error, I think is here:
	`<div class="topbar-section"><a href="{{webPath "/"}}" class="topbar-item">home</a></div>`

In templates/topbar

**Comment by Eggbertx** [comment] 2023-12-06 20:18
> Yes ok I didn't have sqlite installed, sorry I didn't check.

That's strange that it gives you that error about sqlite3, but at least you got that working. Out of curiosity, can you run `go env CGO_ENABLED` and post the output? I'll look and see if there's a way to detect that the issue was caused by sqlite3 not being installed and not because of some other error, to avoid confusion.

As for the home button's behavior, that's caused by the behavior of Go's `path.Join`  function, called by the webPath template function [here](https://github.com/gochan-org/gochan/blob/78fe84ad7fd2761476dd3ea7ad706c85345f2ccb/pkg/config/util.go#L215). It removes the trailing slash unless the result would be an empty string. So even if your WebRoot is set to "/img/" and you call `webPath "/"` from a template, the result will be /img

**Comment by Eggbertx** [comment] 2023-12-07 00:14
I guess that could be done. I'd rather not have it potentially create paths with double slashes, though that could be remedied by having a function specifically intended for directories, that would assume any path given to it is a directory and make sure it turns the joined path with a trailing / and then using that for things like board links and links to the home page

**Comment by Eggbertx** [comment] 2023-12-07 00:16
As for the log issue, I'm not sure what's causing that. Can you confirm that log/ exists? I think I recall seeing a similar "permission denied" error when it tried to open a file in a directory that didn't exist

**Comment by xx1182** [comment] 2023-12-07 11:43
As for the permissions, I've noticed that in the gochan.json there is a value called `Username`:
By changing it to my current username it works, as I don't have nginx, I have no www user, I use caddy as a reverse proxy.

Regards.

**Comment by Eggbertx** [comment] 2023-12-07 16:42
Oh, ok. I'll change the value in the example file to an empty string to avoid confusion. If the Username value is an empty string, it won't try to mess with the file ownership

**Comment by xx1182** [comment] 2023-12-07 18:44
Since I'm here I might as well:
When you edit the board from the /manage setting and apply a style, it doesn't apply it.
Front-End development seems too complicated, couldn't it be just some CSS files rather than scss and node and whatever. It would be just easier.

**Comment by xx1182** [comment] 2023-12-07 19:34
> SCSS is used to make it easier, so you can store values in variables and import mixins and variables used by multiple files, rather than having to repeat the same value in multiple places in a single potentially large file (see [global.css](https://github.com/gochan-org/gochan/blob/master/html/css/global.css)) That said, SCSS and Node aren't called directly by gochan so if you don't want to use them, you can just write straight CSS and put it in html/css/.

Ok, thanks, and what about the last issue where if you change the style(ex: from pipes to windows9x) of a board it doesn't change, can you replicate?

**Comment by Eggbertx** [comment] 2023-12-07 19:55
Yes, I can confirm this, looking into it now. The board's individual style is correctly written to the HTML files, but it gets replaced with the global style by the fontend, working on that now.

**Comment by Eggbertx** [comment] 2023-12-07 21:56
And done, if you're using the latest Git commits (as opposed to the latest release), you should be able to pull changes run `./build.py js`.

If you don't want to install Node, I've attached the frontend built as of commit [d4335cf](https://github.com/gochan-org/gochan/commit/d4335cf5b95d820e29d091cef93d1d1a5aac6f27) here: [js.zip](https://github.com/gochan-org/gochan/files/13605817/js.zip). Unzip the contents into html/js/ and do a hard refresh in your browser, and it should load the board-specific theme correctly, unless you changed your settings, in which case that will override it.

**Comment by xx1182** [comment] 2023-12-08 08:59
> And done, if you're using the latest Git commits (as opposed to the latest release), you should be able to pull changes run `./build.py js`.
> 
> If you don't want to install Node, I've attached the frontend built as of commit [d4335cf](https://github.com/gochan-org/gochan/commit/d4335cf5b95d820e29d091cef93d1d1a5aac6f27) here: [js.zip](https://github.com/gochan-org/gochan/files/13605817/js.zip). Unzip the contents into html/js/ and do a hard refresh in your browser, and it should load the board-specific theme correctly, unless you changed your settings, in which case that will override it.

Thanks again, but the instructions are somewhat unclear:
When `./build.py js` where is the output? In what folder? I used the is from the realease and put it html(documentRoot)

Latest commit has problems, here is log:
```
{"level":"info","dbType":"sqlite3","time":"today","message":"Connected to database"}

{"level":"fatal","error":"error opening database: invalid MaxMind DB file","time":"today"}
```

**Comment by xx1182** [comment] 2023-12-08 16:36
> When you run `./build.py js` the file is written to html/js/gochan.js.
> 
> > Latest commit has problems, here is log:
> 
> Sorry about that, I'm also ironing out the GeoIP functionality. Set GeoIPDBlocation in gochan.json to "", or just remove the entry

Thanks it worked, I've tried setting the geodbtype to the various values with no avail, by removing the string it works, if I have time I'll update all the config/guides accordingly, because you seem ESL too.

Regards.

**Comment by xx1182** [comment] 2023-12-08 16:48
>do a hard refresh in your browser, and it should load the board-specific theme correctly, unless you changed your settings, in which case that will override it.

Ah, I've just checked, it doesn't change.

**Comment by Eggbertx** [comment] 2023-12-08 16:59
> Thanks it worked, I've tried setting the geodbtype to the various values with no avail, by removing the string it works, if I have time I'll update all the config/guides accordingly, because you seem ESL too.

English is my first/primary language, but the documentation has admittedly been kind of lax. I'm also working on improving the configuration docs to make it clearer what everything does.

> Ah, I've just checked, it doesn't change.

Where are you putting your board configuration? It should go in /[board]/board.json

**Comment by Eggbertx** [comment] 2023-12-08 21:22
/boards.json isn't a configuration file, it's part of the (mostly) 4chan-compatible JSON API. It's generated by gochan and doesn't need to be manually edited.

I admittedly forgot that the boards SQL table had a default theme attribute (which the manage page sets/updates).  I'm working on fixing it now. The theme attribute in the SQL will override the global attribute (which it is set to by default), and if /[board]/board.json exists, that will override the theme.

**Comment by xx1182** [comment] 2023-12-09 10:27
Ran in some issues:
(1)The js doesn't "visually save" the changes, when you save it does change, but if you refresh and go on settings again it's not your values.
(2)The "Persistent Quick Reply" can't be disabled, when disabling and saving nothing happens, the only way to remove "Persistent Quick Reply" is to disable "Use Quick Reply box"

(3)This is not a bug but maybe a feature request: 
I have no clue on how node and it's dependencies work, if it were for me I would have just wrote by hand the .CSS files in the static folder, I'm saying this because personally it's way easier(for me) to just modify the global.css to edit the front page, what's your intended way to edit the FrontPage(/)?

**Comment by Eggbertx** [comment] 2023-12-09 20:53
> (1)The js doesn't "visually save" the changes, when you save it does change, but if you refresh and go on settings again it's not your values.
> (2)The "Persistent Quick Reply" can't be disabled, when disabling and saving nothing happens, the only way to remove "Persistent Quick Reply" is to disable "Use Quick Reply box"

Fixed as of [00a02a6](https://github.com/gochan-org/gochan/commit/00a02a699a490f4e97ba8daf6bc6ff14abf0de74).



> I have no clue on how node and it's dependencies work, if it were for me I would have just wrote by hand the .CSS files in the static folder, I'm saying this because personally it's way easier(for me) to just modify the global.css to edit the front page, what's your intended way to edit the FrontPage(/)?

If you have Node.js and NPM installed, from the frontend directory, run `npm install`, and it'll install all of the necessary dependencies for you. After that, you can run `npm build-ts` for building gochan.js or `npm build-sass` for building the CSS styles.



> (4)I have no clue on how to modify the message "Welcome to Gochan!" In the front page, I thought it was "staff announcement" but it's not, and infact staff announcement seems to do nothing.

That is actually not in an announcement. It's in [/templates/front_intro.html](https://github.com/gochan-org/gochan/blob/master/templates/front_intro.html)

As for the announcements page, it does work but they're meant to be private announcements visible on the staff dashboard:

![image](https://github.com/gochan-org/gochan/assets/76852/2824737d-8b1a-4e48-82e4-c17c8e461815)


>  (5)The build script should build in a /bin/ directory so it's easier to manage

You mean output to ./bin? If you run `./build.py install`, it copies gochan and gochan-migrate to /usr/bin and the templates, examples, and SQL initialization files to /usr/share/gochan, but if you think that it should output the binaries to ./bin by default when you just run `./build.py`, I can set it to do that

**Comment by xx1182** [comment] 2023-12-10 08:13
> > Quote
No, about (4) I was wondering if you could remove node dependencies and building completely and just ship individual .CSS files, as this is how I'm modifying the stylesheet, you are referring to building .CSS, with sass(sounds gay btw), by reading the .sass files it seems more complicated than it needs to be. Again, remove sass and node and just ship the CSS for easier front-end development.
(By front-end I refer to the stylesheets not the JS)

As for (5) I think it would be better for the build script to just build in the ./bin directory, with the various files for running (documentroot/templateroot/sqlfiles), personally I don't like to install it, and it's easier to differentiate source from binaries, so this way is straightforward with no reading needed.
Regards.

And thanks again for the quick replies.

**Comment by Eggbertx** [comment] 2023-12-10 22:01
> Yes and no, it now saves settings, but the "persistent quick reply" toggle doesn't work, even by disabling it, the quick reply still floats around. (Just ran ./build.py js and rebuild everything from the /manage page)

Oops, crap, I saved it but I apparently never implemented that setting to be actually used. Now it works as of [72d6b08](https://github.com/gochan-org/gochan/commit/72d6b08a279492ac9d3cebd21cef54bbbddffe16)

> No, about (4) I was wondering if you could remove node dependencies and building completely and just ship individual .CSS files, as this is how I'm modifying the stylesheet, you are referring to building .CSS, with sass(sounds gay btw), by reading the .sass files it seems more complicated than it needs to be. Again, remove sass and node and just ship the CSS for easier front-end development. (By front-end I refer to the stylesheets not the JS)

SCSS itself isn't much more complicated than CSS. It's a superset of the CSS language, meaning any valid CSS is valid SCSS.  It's useful for when you have to repeat a lot of stuff (like values or properties that can be grouped into mixins). Take yotsuba.css and yotsubab.css for example. They're almost identical except for a few details, meaning that keeping track of changes can be tedious, but they can be generated by a Sass mixin, defined in _yotsubacommon.scss. 

And like I mentioned, if you don't want to write scss files, you can just write your css file to the html/css/ directory. If you're wanting to make changes to a theme already in this repo, submit a pull request with your modified css file(s), and I'll update the SCSS source to match.

If your concern is with disk space taken up by the node_modules directory, I'm pretty sure more dependencies are required by Webpack, TypeScript, and the related dependencies used for generating gochan.js, and I'm definitely not going back to writing a single gochan.js file.

> Also can you add a menu for modifying front_intro, for easier of use? I think it's a pretty important part, because it's one of the first messages you see.

Sure. I might just expand this and add an editor for allowing an admin to edit any of the templates from their browser.

> As for (5) I think it would be better for the build script to just build in the ./bin directory, with the various files for running (documentroot/templateroot/sqlfiles), personally I don't like to install it, and it's easier to differentiate source from binaries, so this way is straightforward with no reading needed. Regards.

To make sure I understand, you're saying that the html, sql, and templates directories as well as the executables should be copied to ./bin by `build.py`? I wouldn't be against this. It already does something like this when a release is generated by running `./build.py release`, though it puts it in ./releases/gochan-[version]_[os].

> And thanks again for the quick replies.

Of course. If gochan has ongoing issues that need to be fixed but are left unaddressed, that's a poor reflection on its developer.

**Closed** 2023-12-27 01:05 UTC
Labels: bug
